### ISSUE TITLE
Dont Redirect to App in iOs 13

### ISSUE THREAD

**Issue by adriancsbna** [pikaju/flutter-braintree#39]
Hello

I have updated the plugin to version 1.1.0 in two apps, and in iOs 13, in both cases, when you perform 3D Secure authentication in sandbox mode, the web does not redirect you to the App.

A big blue button appears that tells you that it redirects you to the app if it doesn't do it automatically, but pressing it doesn't redirect you.

You can only get out of there by pressing DONE and the app interprets it as having canceled it.

Do you know what this error could be due to?

Thank you very much
a greeting
Adrian Casabuena

**Comment by marcioadr88** [comment]
same is happening to me

**Comment by nicolobozzato** [comment]
There some workaround for this?

**Comment by nicolobozzato** [comment]
I fix it for me. My problem is that i followed the package example and wrote  this in the AppDelegate.swift
`    override func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        if url.scheme == "com.example.flutterBraintreeExample.payments" {
            return BTAppSwitch.handleOpen(url, options:options)
        }
        
        return false
    }`

instead of this

`func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
    if url.scheme?.localizedCaseInsensitiveCompare("com.example.flutterBraintreeExample.payments") == .orderedSame {
        return BTAppSwitch.handleOpen(url, options: options)
    }
    return false
}`

like I should have look and is shown here https://developers.braintreepayments.com/guides/paypal/client-side/ios/v4

**Comment by pikaju** [comment]
Please try the latest version and reopen if the issue persists.
